// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Visit.DAL;

#nullable disable

namespace Visit.DAL.Migrations
{
    [DbContext(typeof(VisitDbContext))]
    partial class VisitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Visit.DAL.Bimar", b =>
                {
                    b.Property<int>("BimarID")
                        .HasColumnType("int");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)");

                    b.HasKey("BimarID");

                    b.ToTable("Bimars");
                });

            modelBuilder.Entity("Visit.DAL.Chat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ToID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FromID");

                    b.HasIndex("ToID");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Visit.DAL.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<string>("CodeNezamPezeshki")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(5)");

                    b.Property<TimeSpan>("EndWorkingTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartWorkingTime")
                        .HasColumnType("time");

                    b.HasKey("DoctorID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Visit.DAL.Doctor_Takhasos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<byte>("TakhasosID")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("TakhasosID");

                    b.ToTable("Doctor_Takhasoses");
                });

            modelBuilder.Entity("Visit.DAL.ExceptionLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ExceptionLogs");
                });

            modelBuilder.Entity("Visit.DAL.Takhasos", b =>
                {
                    b.Property<byte>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("ID"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Takhasoses");

                    b.HasData(
                        new
                        {
                            ID = (byte)1,
                            Title = "چشم"
                        },
                        new
                        {
                            ID = (byte)2,
                            Title = "مغز و اعصاب"
                        },
                        new
                        {
                            ID = (byte)3,
                            Title = "قلب و عروق"
                        },
                        new
                        {
                            ID = (byte)4,
                            Title = "گوش و حلق و بینی"
                        },
                        new
                        {
                            ID = (byte)5,
                            Title = "اعصاب و روان"
                        },
                        new
                        {
                            ID = (byte)6,
                            Title = "روانشناسی"
                        },
                        new
                        {
                            ID = (byte)7,
                            Title = "اطفال"
                        },
                        new
                        {
                            ID = (byte)8,
                            Title = "پوست و مو زیبایی"
                        },
                        new
                        {
                            ID = (byte)9,
                            Title = "گوارش"
                        },
                        new
                        {
                            ID = (byte)10,
                            Title = "ریه"
                        },
                        new
                        {
                            ID = (byte)11,
                            Title = "کلیه"
                        },
                        new
                        {
                            ID = (byte)12,
                            Title = "غدد"
                        },
                        new
                        {
                            ID = (byte)13,
                            Title = "تغذیه"
                        },
                        new
                        {
                            ID = (byte)14,
                            Title = "پزشک عمومی"
                        },
                        new
                        {
                            ID = (byte)15,
                            Title = "مامایی"
                        });
                });

            modelBuilder.Entity("Visit.DAL.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Visit.DAL.Visit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BimarID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BimarID");

                    b.HasIndex("DoctorID");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Visit.DAL.Bimar", b =>
                {
                    b.HasOne("Visit.DAL.User", "User")
                        .WithOne("Bimar")
                        .HasForeignKey("Visit.DAL.Bimar", "BimarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Visit.DAL.Chat", b =>
                {
                    b.HasOne("Visit.DAL.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("FromID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Visit.DAL.User", "User1")
                        .WithMany("Chats1")
                        .HasForeignKey("ToID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("User1");
                });

            modelBuilder.Entity("Visit.DAL.Doctor", b =>
                {
                    b.HasOne("Visit.DAL.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Visit.DAL.Doctor", "DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Visit.DAL.Doctor_Takhasos", b =>
                {
                    b.HasOne("Visit.DAL.Doctor", "Doctor")
                        .WithMany("Doctor_Takhasoses")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Visit.DAL.Takhasos", "Takhasos")
                        .WithMany("Doctor_Takhasoses")
                        .HasForeignKey("TakhasosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Takhasos");
                });

            modelBuilder.Entity("Visit.DAL.Visit", b =>
                {
                    b.HasOne("Visit.DAL.Bimar", "Bimar")
                        .WithMany("Visits")
                        .HasForeignKey("BimarID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Visit.DAL.Doctor", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bimar");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Visit.DAL.Bimar", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Visit.DAL.Doctor", b =>
                {
                    b.Navigation("Doctor_Takhasoses");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Visit.DAL.Takhasos", b =>
                {
                    b.Navigation("Doctor_Takhasoses");
                });

            modelBuilder.Entity("Visit.DAL.User", b =>
                {
                    b.Navigation("Bimar");

                    b.Navigation("Chats");

                    b.Navigation("Chats1");

                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
